My-BaseCamp_2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :users
  resources :messages, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :replies, only: [:create, :update, :edit, :destroy] do
      delete '/', to: 'replies#destroy', on: :collection
    end
  end
  
  delete '/replies/:id', to: 'replies#destroy', as: 'destroy_reply'

  get '/users', to: 'users#index'
  patch 'users/:id/update_role', to: 'users#update_role', as: 'update_role'
  root 'home#index'
end

My-BaseCamp_2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects, dependent: :nullify
  has_many :messages, foreign_key: :user_id
  has_many :replies, through: :messages
end

My-BaseCamp_2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        if current_user.role == 1
            @users = User.all
        else
            redirect_to user_path(current_user)
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(permitted_params)
        if @user.save
            redirect_to users_path
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
            if @user.errors.any?
                render :edit
            else
                redirect_to @user, notice: 'User updated successfully'
            end
    end

    def update_role
        @user = User.find(params[:id])
        @user.update(role_params)
        notice = 'Role updated successfully'
    end

    def show
        if params[:id] == 'sign_out'
            sign_out
            redirect_to root_path
        else
          @user = User.find(params[:id])
        end
    end
      
    def destroy
        #disassociating user
        @user = User.find(params[:id])
        @user.projects.update_all(user_id: nil)
        @user.messages.update_all(user_id: nil)
        @user.replies.update_all(user_id: nil)
        @user.destroy
      
        redirect_to users_path
      end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation)
    end

    def permitted_params
        params.require(:user_registration).permit(:email, :password, :password_confirmation, :admin)
    end

    def role_params
        params.require(:user).permit(:role)
    end

    def password_confirmation_matches
        if params[:user][:password].present? && params[:user][:password_confirmation].present?
          if params[:user][:password] != params[:user][:password_confirmation]
            # add an error to the @user object
            @user.errors.add(:password_confirmation, "must match password")
          end
        end
    end
end

My-BaseCamp_2/app/helpers/users_helper.rb
module UsersHelper
end

My-BaseCamp_2/app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="card mx-auto" style="max-width: 600px; border: 1px solid #ccc;">
    <div class="card-body">
      <h1 class="card-title text-center mb-4">Edit <%=@user.first_name%></h1>

     <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being updated:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, disabled: true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= f.submit "Update #{@user.first_name}", class: "btn btn-primary" %>
          <%= link_to "Cancel", users_path, class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

My-BaseCamp_2/app/views/users/index.html.erb
<div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 10vh;">
    <h2> All Users </h2>
    </div>

<table class="table table-hover table-bordered table-striped table-plain" style="width: 100%; text-align: center; border: 2px solid #ccc; border-collapse: collapse; padding: 10px; margin-bottom: 20px; font-family: Arial, sans-serif; font-size: 14px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email Address</th>
      <th>Role</th>
      <th>Modify</th>
    </tr>
  </thead>
  <tbody>
  
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
        <td><%= user.email%></td>
        <td><%= user.role == 0 ? "User" : "Admin" %></td>
        <td>
        <div class="btn-group">
          <%=link_to "Edit", edit_user_path(user), class: "btn btn-primary"%>&emsp;
    
          <% if user.role == 0 %>
            <%= button_to "Make Admin", update_role_path(user), params: { user: { role: 1 } }, method: :patch, class: "btn btn-success", onclick: "refreshPage()" %>
            <% else %>
              <%= button_to "Remove Admin", update_role_path(user), params: {user: {role: 0} }, method: :patch, class: "btn btn-danger", onclick: "refreshPage()" %>
            <% end %>
        </div>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>
<script>
  function refreshPage() {
    location.reload();
  }
</script>

My-BaseCamp_2/app/views/users/show.html.erb
<div class="table-responsive">
  <table class="table">
    <tbody>
      <tr class="table-bordered table-striped ">
        <td><strong>First Name</td>
        <td><%= @user.first_name %></td>
      </tr>
      <tr class="table-bordered table-striped r">
        <td><strong>Last Name</td>
        <td><%= @user.last_name %></td>
      </tr>
      <tr class="table-bordered table-striped ">
        <td><strong>Email</td>
        <td><%= @user.email %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="btn-group">
  <%=link_to "Edit", edit_user_path(@user), class: "btn btn-primary"%>&emsp;
  <%= button_to "Delete Account", user_path(@user), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, remote: true, class: "btn btn-danger"%>&emsp;
<%= link_to "Cancel", root_path, class: "btn btn-success" %></div>


<script>
  // handle the success response from the server
  function handleDeleteSuccess() {
    Turbo.visit('/logout');
  }

  // listen for the click event on the delete button
  document.getElementById('delete-user').addEventListener('ajax:success', handleDeleteSuccess);
</script>