My-BaseCamp_2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :users
  resources :messages, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :replies, only: [:create, :update, :edit, :destroy] do
      delete '/', to: 'replies#destroy', on: :collection
    end
  end
  
  delete '/replies/:id', to: 'replies#destroy', as: 'destroy_reply'

  get '/users', to: 'users#index'
  patch 'users/:id/update_role', to: 'users#update_role', as: 'update_role'
  root 'home#index'
end

My-BaseCamp_2/app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :parent_message, class_name: 'Message', optional: true
  has_many :replies, dependent: :destroy
end

My-BaseCamp_2/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_message, only: [:show, :edit, :update, :destroy, :create_reply]
	before_action :valid_user, only: [:new, :create, :create_reply]
  
	def index
		@messages = Message.where(parent_message_id: nil)
	end
  
	def new
	  @message = Message.new
	end
  
	def create
	  @message = current_user.messages.build(message_params)
  
	  if @message.save
		redirect_to message_path(@message), notice: "Message was successfully created."
	  else
		render :new, status: :unprocessable_entity
	  end
	end
  
	def edit
	end
  
	def update
		if @message.update(message_params)
			redirect_to message_path(@message), notice: "Message was successfully updated."
		else
			render :edit, status: :unprocessable_entity
		end
	end
  
	def destroy
	  @message.destroy
  
	  respond_to do |format|
		format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
		format.json { head :no_content }
	  end
	end
  
	def show
	  @message = Message.find(params[:id])
	  @replies = @message.replies
	  @reply = Reply.new
	end
  
	private
  
	def message_params
		params.require(:message).permit(:content)
	end

	def set_message
		@message = Message.find_by(id: params[:id])
		
		if @message.nil?
		  redirect_to messages_path, notice: "The requested message could not be found."
		end
	end
	  
  
	def valid_user
		unless current_user.role == 1
		redirect_to messages_path, notice: "Unauthorized access"
		end
	end
  
end

My-BaseCamp_2/app/helpers/messages_helper.rb
module MessagesHelper
end

My-BaseCamp_2/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this thread from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li> 
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :@user_id, value: current_user.id %>  
 
  <div class="form-group">
  <%= form.text_area :content, class: "form-control", id: "content", rows: 3, placeholder: "What's on your mind?" %>
</div>

<div classname="last" style="display: flex; justify-content: space-between">
  <%= form.submit "Post Thread", class:"btn btn-primary" %>
<% end %>

My-BaseCamp_2/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path, class: "btn btn-primary" %>
</div>

My-BaseCamp_2/app/views/messages/index.html.erb
<div classname="header" style="display:flex; justify-content: space-between; align-items: center">
	<h1>Threads</h1>
<% unless current_user.role == 0 %>
  <%= link_to "New Thread", new_message_path, class: "btn btn-primary" %>
<% end %>
</div>

<div class="table-responsive">
  <table class="table table-hover table-bordered table-striped table-plain" style="width: 100%; text-align: center; border: 2px solid #ccc; border-collapse: collapse; padding: 10px; margin-bottom: 20px; font-family: Arial, sans-serif; font-size: 14px;">
    <thead class="table-secondary">
      <tr>
        <th scope="col">Thread Content</th>
        <th scope="col">Author</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= truncate(message.content, length: 120) %></td>
          <td><%= User.find_by(id: message.user_id) ? User.find(message.user_id).first_name + ' ' + User.find(message.user_id).last_name : 'Deleted user' %></td>

          <td>
            <div class="btn-group" role="group" aria-label="Message actions">
              <%= link_to "Show", message, class: "btn btn-success" %>&emsp;
              <% if current_user.role == 1 %>
                <%= link_to "Edit", edit_message_path(message), class: "btn btn-secondary" %>&emsp;
                <%= button_to "Delete", message, method: :delete, data: { confirm: "Are you sure you want to delete this reply?" }, class: "btn btn-danger" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% unless current_user.role == 0 %>
  <%= link_to "New Thread", new_message_path, class: "btn btn-primary" %>
<% end %>

My-BaseCamp_2/app/views/messages/new.html.erb
<h1>New Thread</h1>
<br>
<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path, class: "btn btn-info"%>
</div>

My-BaseCamp_2/app/views/messages/show.html.erb
<div class="message-thread">
  <h1><%= User.find(@message.user_id).first_name.upcase + " " + User.find(@message.user_id).last_name.upcase + "'s Post" %></h1>

  <div class="message-content-container">
    <div class="message-content">
      <%= @message.content %>
    </div>
  </div>

  <% @message.replies.each do |reply| %>
    <div class="reply-container">
      <div class="reply-content">
        <%= reply.content %>
      </div>

      <div class="reply-actions">
      <%if current_user.role == 1 || current_user == reply.user%>
        <%= link_to "Edit", edit_message_reply_path(@message, reply), class:"edit-link"%>
        <%= button_to "Delete", message_reply_path(@message, reply), method: :delete, data: { confirm: "Are you sure you want to delete this reply?" }, class: "delete-link"  %>
      <%end%>
      </div>
    </div>
  <% end %>
  
  <%= form_with(model: [@message, @reply], url: message_replies_path(@message.id)) do |form| %>
    <div class="form-group">
      <%= form.label :Reply %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Reply", class: "btn btn-primary" %>
      <% unless current_user.role == 0 %>
        <%= link_to "Edit", edit_message_path(@message), class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back to Messages", messages_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<br>