My-BaseCamp_2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :users
  resources :messages, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :replies, only: [:create, :update, :edit, :destroy] do
      delete '/', to: 'replies#destroy', on: :collection
    end
  end
  
  delete '/replies/:id', to: 'replies#destroy', as: 'destroy_reply'

  get '/users', to: 'users#index'
  patch 'users/:id/update_role', to: 'users#update_role', as: 'update_role'
  root 'home#index'
end

My-BaseCamp_2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

My-BaseCamp_2/app/helpers/home_helper.rb
module HomeHelper
end

My-BaseCamp_2/app/views/home/_bootstrap.html.erb
<nav class="navbar navbar-dark bg-secondary navbar-expand-lg">
  <div class="container-fluid">
    <%=link_to "Basecamp", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

         <%if user_signed_in?%>

          <li class="nav-item">
            <%=link_to "Projects", projects_path, class: "nav-link active"%>
          </li>
          
            <li class="nav-item">
              <%= link_to "Threads", messages_path, class: "nav-link active" %>
            </li>

          <%if current_user.role == 1%>

          <li class="nav-item">
            <%=link_to "Users", users_path, class: "nav-link active"%>
          </li>
          <%end%>
          <li class="nav-item">
            <%=link_to "Profile", user_path(current_user.id), class: "nav-link active"%>
          </li>

          <li class="nav-item">
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link active", data: { turbolinks: false } %>
</li>

             
          <li class="nav-item nav-link disabled"> <%= current_user.email %></li>
          <%end%>
        
      </div>
    </div>
  </div>
</nav>

My-BaseCamp_2/app/views/home/index.html.erb
<%if !user_signed_in?%>
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 70vh;">
    <h1>Welcome to BaseCamp</h1>
    <div class="row mt-4">

      
      <div class="col-sm-6 mb-2">
        <%= link_to "Log in",  user_session_path, class: "btn btn-dark btn-block" %>
      </div>

      <div class="col-sm-6">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary btn-block" %>
      </div>
    </div>
  </div>
<%else%>
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 15vh;">
    <h1>Welcome to BaseCamp</h1>
    <div class="row mt-4">
    <p><em>You are logged in as <%= link_to current_user.email%></p>
    </div>
<%end%>